import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import { LayoutProvider } from '@/hooks/use-layout';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home Layout',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LayoutProvider>
      <div className="bg-background relative z-10 flex min-h-svh flex-col">
        <Header />
        <main className="flex flex-1 justify-center flex-col">{children}</main>
        <Footer />
      </div>
    </LayoutProvider>
  );
}
